config/routes.rb
Rails.application.routes.draw do

  get "contact", to: "contact#contact"

  resources :restaurants do
    resources :reviews, only: [:index, :new, :create, :destroy]
  end

  resources :menu, only: [:new, :create, :edit, :update, :destroy, :index]
  get '/menu/:category_id', to: 'menu#category', as: :menu_category

  get 'categories', to: 'categories#index'

  post 'add_to_cart', to: 'items#add_to_cart', as: :add_to_cart

  resource :cart, only: [:show] do
    delete 'clear', on: :collection
    post 'remove_one', on: :collection
  end

  resources :orders, only: [:create, :index, :show]
  patch 'orders/:id/cancel', to: 'orders#cancel', as: :cancel_order
  delete 'orders/:id', to: 'orders#destroy', as: :delete_order
  patch 'orders/:order_id/items/:id/update_quantity', to: 'orders#update_quantity', as: :update_order_item_quantity
  delete 'orders/:order_id/items/:item_id', to: 'orders#destroy_item', as: :delete_order_item
  patch 'orders/:id/update_status', to: 'orders#update_status', as: :update_order_status

  root 'restaurants#index'

  get "password", to: "password#edit", as: "edit_password"
  patch "password", to: "password#update"
  post "password", to: "password#create"


  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"

  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "profile/edit", to: "profile#edit"
  patch "profile/edit", to: "profile#update"
  post "profile/edit", to: "profile#create"

  match '*path', to: 'restaurants#index', via: :all
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart_items = session[:cart].present? ? Menu.find(session[:cart].keys) : []
  end

  def clear
    session.delete(:cart)
    redirect_to cart_path, notice: 'Cart cleared!'
  end
  def remove_one
    item_id = params[:item_id]
    session[:cart][item_id] -= 1 if session[:cart][item_id] && session[:cart][item_id] > 0
    session[:cart].delete(item_id) if session[:cart][item_id] <= 0
    redirect_to cart_path, notice: 'One item removed from cart!'
  end

end

app/views/carts/show.html.erb
<div class="">
  <div class="row justify-content-center">
    <div class="">
      <div>
        <h1 class="bg-primary text-white text-center">Cart</h1>
      </div>
      <div class="">
        <div id="">
          <% if @cart_items.present? && @cart_items.any? %>
            <ul class="list-group">
              <% total_price = 0 %>
              <% @cart_items.each do |item| %>
                <% quantity = session[:cart][item.id.to_s] %>
                <% quantity = quantity.is_a?(Array) ? quantity.first : quantity %>
                <% quantity = quantity.is_a?(Numeric) ? quantity : 1 %>
                <% subtotal = item.price * quantity %>
                <% total_price += subtotal %>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <%= item.item_name %> x<%= quantity %>
                  <div>
                    <div class="badge bg-danger text-center container-fluid">$<%= subtotal %></div>
                    <%= button_to 'Remove one', remove_one_cart_path(item_id: item.id), method: :post, remote: true, class: 'btn btn-warning btn-sm' %>
                  </div>
                </li>
              <% end %>
            </ul>
            <div class="row">
              <div class="col mt-3 text-right">
                <%= button_to 'Clear cart', clear_cart_path, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              </div>
              <div class="col-md-2 mt-4 text-center container-fluid">
                <p><strong>Total: </strong>$<%= total_price %></p>
              </div>
              <div class="col-md-2 mt-3">
                <%= button_to 'Order', orders_path, method: :post, class: 'btn btn-success text-center container-fluid' %>
              </div>
            </div>
          <% else %>
            <p class="text-center">Your cart is empty</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>