config/routes.rb
Rails.application.routes.draw do

  get "contact", to: "contact#contact"

  resources :restaurants do
    resources :reviews, only: [:index, :new, :create, :destroy]
  end

  resources :menu, only: [:new, :create, :edit, :update, :destroy, :index]
  get '/menu/:category_id', to: 'menu#category', as: :menu_category

  get 'categories', to: 'categories#index'

  post 'add_to_cart', to: 'items#add_to_cart', as: :add_to_cart

  resource :cart, only: [:show] do
    delete 'clear', on: :collection
    post 'remove_one', on: :collection
  end

  resources :orders, only: [:create, :index, :show]
  patch 'orders/:id/cancel', to: 'orders#cancel', as: :cancel_order
  delete 'orders/:id', to: 'orders#destroy', as: :delete_order
  patch 'orders/:order_id/items/:id/update_quantity', to: 'orders#update_quantity', as: :update_order_item_quantity
  delete 'orders/:order_id/items/:item_id', to: 'orders#destroy_item', as: :delete_order_item
  patch 'orders/:id/update_status', to: 'orders#update_status', as: :update_order_status

  root 'restaurants#index'

  get "password", to: "password#edit", as: "edit_password"
  patch "password", to: "password#update"
  post "password", to: "password#create"


  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"

  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "profile/edit", to: "profile#edit"
  patch "profile/edit", to: "profile#update"
  post "profile/edit", to: "profile#create"

  match '*path', to: 'restaurants#index', via: :all
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @restaurants = RestaurantsList.search(
      name: params[:search_name],
      city: params[:search_city],
      category: params[:search_category]
    )

    @restaurants.each do |restaurant|
      restaurant.image_base64 = Base64.encode64(restaurant.image) if restaurant.image.present?
    end
  end

  def show
    @restaurant = RestaurantsList.find(params[:id])
  end

  def new
    @restaurant = RestaurantsList.new
  end

  def create
    @restaurant = RestaurantsList.new(restaurant_params)
    if @restaurant.save
      save_image
      redirect_to restaurants_path, notice: "Restaurant added successfully!"
    else
      render :new
    end
  end

  def edit
    @restaurant = RestaurantsList.find(params[:id])
  end

  def update
    @restaurant = RestaurantsList.find(params[:id])

    if @restaurant.update(restaurant_params)
      save_image
      redirect_to restaurants_path, notice: "Restaurant updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @restaurant = RestaurantsList.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, notice: "Restaurant deleted successfully!"
  end

  private

  def restaurant_params
    params.require(:restaurants_list).permit(:name, :category, :description, :city, :address, :image)
  end

  def save_image
    image_data = params[:restaurants_list][:image]
    if image_data.present?
      new_image_data = image_data.read
      @restaurant.image = new_image_data
      @restaurant.save
    end
  end

  def require_admin
    unless Current.user&.admin?
      flash[:alert] = "You don't have permission to access this page."
      redirect_to restaurants_path
    end
  end
end

app/views/restaurants/edit.html.erb
<div class="">
  <div class="row justify-content-center">
    <div class="">
      <div class="">
        <div class=" bg-primary text-white">
          <h1 class="text-center">Edit Restaurant</h1>
        </div>
        <div class="p-3">
          <%= form_with(model: @restaurant, url: restaurant_path(@restaurant), local: true) do |form| %>
            <div class="mb-3">
              <%= form.label :name, class: "form-label" %>
              <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :category, class: "form-label" %>
              <%= form.text_field :category, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :description, class: "form-label" %>
              <%= form.text_area :description, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :city, class: "form-label" %>
              <%= form.text_field :city, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :address, class: "form-label" %>
              <%= form.text_field :address, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :image, class: "form-label" %>
              <%= form.file_field :image, class: "form-control", accept: "image/*" %>
            </div>
            <%= form.submit "Update Restaurant", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="bg-primary text-white p-3 mb-3">
        <h1 class="text-center">Restaurants</h1>
      </div>
      <div class="row menu-items align-items-stretch p-3 bg-white">
        <div class="mb-3">
          <%= form_tag restaurants_path, method: :get, remote: true, class: "form-inline justify-content-center" do %>
            <div class="form-row w-100 justify-content-center">
              <div class="input-group col-lg-3 col-md-4 mb-2">
                <%= text_field_tag :search_name, params[:search_name], class: "form-control", placeholder: "Search by name..." %>
              </div>
              <div class="input-group col-lg-3 col-md-4 mb-2">
                <%= text_field_tag :search_city, params[:search_city], class: "form-control", placeholder: "Search by city..." %>
              </div>
              <div class="input-group col-lg-3 col-md-4 mb-2">
                <%= text_field_tag :search_category, params[:search_category], class: "form-control", placeholder: "Search by category..." %>
              </div>
              <div class="input-group col-lg-3 col-md-4 mb-2">
                <button type="submit" class="btn btn-primary w-100">Search</button>
              </div>
            </div>
          <% end %>
        </div>



        <% @restaurants.each do |restaurant| %>
          <div class="col-lg-3 p-2 card-body">
            <div class="menu-item shadow d-flex flex-column h-100">
              <div class="menu-item-image shadow">
                <% if Current.user&.admin? %>
                  <%= link_to edit_restaurant_path(restaurant), method: :get do %>
                    <%= image_tag("data:image/png;base64,#{restaurant.image_base64}", alt: "Restaurant Image", class: "img-fluid rounded-top") if restaurant.image_base64.present? %>
                  <% end %>
                <% else %>
                  <%= link_to categories_path, method: :get do %>
                    <%= image_tag("data:image/jpg;base64,#{restaurant.image_base64}", alt: "Restaurant Image", class: "img-fluid rounded-top") if restaurant.image_base64.present? %>
                  <% end %>
                <% end %>
              </div>
              <div class="d-flex flex-column justify-content-between">
                <div>
                  <% if Current.user&.admin? %>
                    <%= link_to edit_restaurant_path(restaurant), class: "nav-link", method: :get do %>
                      <h2><%= restaurant.name %></h2>
                    <% end %>
                  <% else %>
                    <%= link_to categories_path, class: "nav-link" do %>
                      <h2><%= restaurant.name %></h2>
                    <% end %>
                  <% end %>
                  <p><%= restaurant.description %></p>
                  <p><strong>Category:</strong> <%= restaurant.category %></p>
                  <p><strong>City:</strong> <%= restaurant.city %></p>
                  <p><strong>Address:</strong> <%= restaurant.address %></p>
                  <%= link_to 'Write a review', new_restaurant_review_path(restaurant), class: 'btn btn-primary' %>
                  <%= link_to "View reviews", restaurant_reviews_path(restaurant), class: "btn btn-secondary" %>
                  <% if Current.user&.admin? %>
                    <%= button_to 'Delete', restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="">
  <div class="row justify-content-center">
    <div class="">
      <div class="">
        <div class="bg-primary text-white">
          <h1 class="text-center">Add New Restaurant</h1>
        </div>
        <div class="p-3">
          <%= form_with(model: @restaurant, url: restaurants_path, local: true) do |form| %>
            <div class="mb-3">
              <%= form.label :name, class: "form-label" %>
              <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :category, class: "form-label" %>
              <%= form.text_field :category, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :description, class: "form-label" %>
              <%= form.text_area :description, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :city, class: "form-label" %>
              <%= form.text_field :city, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :address, class: "form-label" %>
              <%= form.text_field :address, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :image, class: "form-label" %>
              <%= form.file_field :image, class: "form-control", accept: "image/*" %>
            </div>
            <%= form.submit "Add Restaurant", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>